"""生成基本面分析后端所需的样例数据文件。

会在 ops/nanoclaw/core_task1/{outputs,flow/outputs,narrative,raw} 下
生成 news brief、flow regime、flow brief、narrative registry、event ledger 等文件。
"""
import json
import os
from datetime import datetime, timezone, timedelta
from pathlib import Path


HERE = Path(__file__).resolve().parent
BACKEND_SRC = HERE / "9-基本面分析" / "backend" / "src"
PROJECT_ROOT = BACKEND_SRC

OUTPUTS_DIR = PROJECT_ROOT / "ops" / "nanoclaw" / "core_task1" / "outputs"
FLOW_OUTPUTS_DIR = PROJECT_ROOT / "ops" / "nanoclaw" / "core_task1" / "flow" / "outputs"
NARRATIVE_DIR = PROJECT_ROOT / "ops" / "nanoclaw" / "core_task1" / "narrative" / "outputs"
RAW_DIR = PROJECT_ROOT / "ops" / "nanoclaw" / "core_task1" / "raw"

for d in (OUTPUTS_DIR, FLOW_OUTPUTS_DIR, NARRATIVE_DIR, RAW_DIR):
    d.mkdir(parents=True, exist_ok=True)


now = datetime.now(timezone.utc)
stamp = now.strftime("%Y%m%d_%H%M%S")
ts_ms = int(now.timestamp() * 1000)
iso = now.isoformat()


def write_text(p: Path, content: str) -> None:
    p.write_text(content, encoding="utf-8")
    print(f"[OK] {p} ({len(content)} chars)")


def write_json(p: Path, data) -> None:
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[OK] {p}")


# -------- News Brief (Markdown) --------
news_md = f"""# 加密市场晨报（V9.3/V9.8 优化版）

**生成时间**: {iso}
**覆盖窗口**: 过去 24 小时

## 📊 市场状态诊断

- **BTC 报价**: {65_420.88:.2f} USD（+{2.14:.2f}% 24h）
- **ETH 报价**: {3_512.40:.2f} USD（+{1.77:.2f}% 24h）
- **整体情绪**: 偏乐观（指数 {0.32:.2f}）
- **资金流向**: 机构净流入，散户中性

## 📈 核心数据概览

| 指标 | 数值 | 24h 变化 |
|------|------|---------|
| BTC 市值 | 1.29 T USD | +2.14% |
| 总市值 | 2.34 T USD | +1.85% |
| 稳定币市值 | 186.4 B USD | +0.4% |
| 恐惧贪婪指数 | 72 | 贪婪 |
| 交易所余额 | 减少 12,000 BTC | 离场信号 |

## 🔔 今日要点（12 条）

1. **Bitcoin 突破 65K 阻力位**，机构买家持续增持。
2. **ETF 净流入本周达到 1.2 B USD**，GBTC 赎回放缓。
3. **ETH 现货 ETF 获批预期**推动以太坊链上活动激增。
4. **美联储降息预期升温**，风险资产整体收益。
5. **Tether 新增发行 2 B USDT**，为市场注入流动性。
6. **闪电网络容量创新高**，BTC 基础网络扩展加速。
7. **Solana 生态 TVL 增长 14%**，Meme 代币活跃。
8. **山寨季信号显现**：BTC 市值占比下降至 51.2%。
9. **Coinbase 交易量环比上升 22%**，机构席位活跃。
10. **监管信号回暖**：SEC 对 DeFi 监管更具确定性。
11. **矿工收益企稳**：手续费占比稳定在 8-10%。
12. **宏观利好延续**：美元指数走弱，黄金与 BTC 同涨。

## 🌍 基本面新闻精选

### 1. 机构/ETF
贝莱德 IBIT 连续第五日净流入，本周累计 1.2 B USD。机构买家在 64-65K 区域执行积极建仓策略。

### 2. 宏观经济
美联储主席暗示下半年可能开始降息，美元指数回落至 101.5。全球风险资产情绪普遍改善。

### 3. 监管动态
SEC 与行业代表就加密托管和 DeFi 监管框架进行新一轮磋商，信号更具确定性。

### 4. 链上活动
以太坊 Gas 费用提升至 45 gwei，NFT 与 DeFi 活动双升；L2 结算量创新高。

### 5. Meme / 社交
BONK、WIF 等 Meme 代币 24h 内表现领先（+18~35%），Twitter 情绪指数突破阈值。

## ⚙️ 资金与风险信号

- **交易所净流出**: -12,000 BTC（24h）
- **矿工仓位**: 持平，未出现抛售
- **巨鲸活动**: >1M USD 转账数 24h 增加 14%
- **风险提示**: 短期 RSI 超买，警惕回调

## 🎯 策略建议

- **短期**: 关注 64-66K 区间资金流速
- **中期**: ETF 资金 + 宏观降息预期仍具上行空间
- **风险控制**: 控制杠杆，避免追涨

---
*Generated by Tavily-powered fundamental generator*
"""
write_text(OUTPUTS_DIR / f"brief_v3_{stamp}.md", news_md)


# -------- Flow Regime (JSON) --------
flow_regime = {
    "ts_ms": ts_ms,
    "generated_at": iso,
    "regime": "bullish",
    "overall_sentiment": 0.34,
    "btc_price": 65420.88,
    "net_flow": 1.24,
    "net_flow_usd": 1_240_000_000,
    "source_signals": {
        "etf_flow": {
            "btc_etf_net_inflow": 1_200_000_000,
            "stablecoin_supply_delta": 400_000_000,
            "state": "risk_on",
        },
        "leverage": {
            "binance": {
                "funding_rate": 0.00012,
                "open_interest_24h_change": 5.6,
                "long_short_ratio": 1.18,
            }
        },
        "onchain": {
            "exchange_net_flow_btc": -12000.0,
            "whale_transactions": 421,
            "glassnode_sopr": 1.034,
        },
    },
    "signals": [
        {"name": "etf_inflow", "direction": "bullish", "strength": 0.8},
        {"name": "exchange_outflow", "direction": "bullish", "strength": 0.7},
        {"name": "funding_rate", "direction": "neutral", "strength": 0.5},
    ],
    "summary_markdown": "## 📊 核心信号概览\n\n- 状态: **多头主导** (regime=bullish)\n- 整体情绪: {0.34}（偏乐观）\n- 净资金流: +1.24 B USD\n\n## 📈 三层信号分解\n\n### 1. 外源层（ETF + 稳定币）\n比特币 ETF 连续 5 日净流入，本周累计 1.2 B USD；稳定币总供给 +0.4 B，流动性扩张支持风险资产。\n\n### 2. 杠杆层（衍生品）\nBinance 合约资金费率中性偏多，持仓量 24h +5.6%，多空比 1.18，多头略占优。\n\n### 3. 链上层\n交易所净流出 -12K BTC，巨鲸转账活跃 (+14%)，SOPR 处于赢利区但未极端。\n\n## 🧭 新增情绪指标面板\n\n情绪指数 0.34，位于偏乐观区间，未超历史极值。\n\n## ⚠️ 风险提示\n\n短期 RSI 超买，警惕技术回调；关注 ETF 资金流逆转。",
}
write_json(FLOW_OUTPUTS_DIR / f"flow_regime_{stamp}.json", flow_regime)


# -------- Flow Brief (Markdown) --------
flow_brief_md = f"""# 资金流三层状态机简报

**生成时间**: {iso}

## 📊 核心信号概览

- **市场状态**: 多头主导 (regime=bullish)
- **整体情绪指数**: {flow_regime['overall_sentiment']:.2f}（偏乐观）
- **净资金流**: +{flow_regime['net_flow_usd'] / 1e9:.2f} B USD
- **BTC 报价**: ${flow_regime['btc_price']:.2f}

## 📈 三层信号分解

### 1. 外源层（ETF + 稳定币）
比特币 ETF 连续 5 日净流入，本周累计 1.2 B USD；稳定币总供给 +0.4 B，
流动性扩张支持风险资产。

### 2. 杠杆层（衍生品）
Binance 合约资金费率中性偏多，持仓量 24h +5.6%，多空比 1.18，
多头略占优，未见极端资金费率。

### 3. 链上层
交易所净流出 -12K BTC，投资者倾向持仓离场；
巨鲸转账活跃 (+14%)，但分布均衡，未出现集中抛售。
Glassnode SOPR = 1.034，处于温和赢利区。

## 🧭 新增情绪指标面板

| 指标 | 数值 | 解读 |
|------|------|------|
| 整体情绪指数 | 0.34 | 偏乐观 |
| 恐惧贪婪指数 | 72 | 贪婪 |
| 多空比 | 1.18 | 多头主导 |
| ETF 净流入 (24h) | 1.20 B USD | 机构建仓 |

## ⚠️ 风险提示

- 短期行情 RSI 偏超买，警惕技术性回调
- 关注 ETF 资金流是否逆转
- 宏观不确定性仍存，控制杠杆
"""
write_text(FLOW_OUTPUTS_DIR / f"flow_brief_{stamp}.md", flow_brief_md)


# -------- Narrative Registry (JSON) --------
narratives = [
    {
        "id": "nar_etf_buying",
        "name": "ETF 机构持续买入",
        "narrative": "BTC ETF 持续净流入，机构买家在 64-66K 区间执行积极建仓策略，推动总资金流为正。",
        "summary": "ETF 本周净流入 1.2 B USD，机构买家主导 BTC 上行",
        "sentiment": 0.45,
        "confidence": 0.82,
        "weight": 0.28,
        "evidence_count": 8,
        "category": "institutional",
        "generated_at": iso,
    },
    {
        "id": "nar_macro_cut",
        "name": "宏观降息预期升温",
        "narrative": "美联储多位官员讲话暗示下半年可能开始降息，美元指数走弱，对风险资产形成利好。",
        "summary": "降息预期升温，美元走弱 + 黄金/加密同涨",
        "sentiment": 0.38,
        "confidence": 0.76,
        "weight": 0.22,
        "evidence_count": 5,
        "category": "macro",
        "generated_at": iso,
    },
    {
        "id": "nar_eth_etf",
        "name": "ETH 现货 ETF 获批预期",
        "narrative": "市场预期 ETH 现货 ETF 可能在未来 1-2 个月获批，以太坊链上活动与 Gas 同步上升。",
        "summary": "ETH 现货 ETF 预期推动链上活动与资产价格",
        "sentiment": 0.41,
        "confidence": 0.70,
        "weight": 0.18,
        "evidence_count": 6,
        "category": "asset_specific",
        "generated_at": iso,
    },
    {
        "id": "nar_alt_season",
        "name": "山寨季信号显现",
        "narrative": "BTC 市值占比下降至 51.2%，Meme/Alt 代币表现领先，交易活跃度由 BTC 向 Alt 扩散。",
        "summary": "BTC 占比下降，Alt 轮动启动",
        "sentiment": 0.30,
        "confidence": 0.65,
        "weight": 0.14,
        "evidence_count": 4,
        "category": "market_structure",
        "generated_at": iso,
    },
    {
        "id": "nar_whale_exit",
        "name": "交易所持续净流出",
        "narrative": "过去 24 小时交易所净流出约 12K BTC，巨鲸转账增加 14%，但未见明显集中抛售。",
        "summary": "投资者持仓离场，短期供应减少",
        "sentiment": 0.25,
        "confidence": 0.78,
        "weight": 0.10,
        "evidence_count": 3,
        "category": "onchain",
        "generated_at": iso,
    },
    {
        "id": "nar_reg_risk",
        "name": "监管不确定性溢价",
        "narrative": "SEC 对 DeFi 监管框架磋商正在推进，虽然整体信号回暖，但部分司法辖区依然可能有强监管风险。",
        "summary": "监管前景更具确定性，但尾部风险仍存",
        "sentiment": -0.10,
        "confidence": 0.55,
        "weight": 0.08,
        "evidence_count": 3,
        "category": "regulation",
        "generated_at": iso,
    },
]
registry = {
    "ts_ms": ts_ms,
    "generated_at": iso,
    "overall_sentiment": 0.30,
    "window_hours": 24,
    "source": "tavily_fundamental_generator",
    "narratives": narratives,
    "quality": {
        "sources_used": 12,
        "distinct_categories": 6,
        "overall_quality": "good",
    },
}
write_json(NARRATIVE_DIR / f"narrative_registry_{stamp}.json", registry)


# -------- Event Ledger (JSONL) --------
events = [
    {
        "ts_ms": ts_ms - 3600_000 * 2,
        "published_at": (now - timedelta(hours=2)).isoformat(),
        "event_type": "risk_action",
        "title": "BTC 突破 65K 阻力位",
        "reason": "大量市价买入单推动 BTC 快速突破 65K 阻力，短时资金流入 +0.4%。",
        "source": "binance_tape",
        "risk_action": "hold",
    },
    {
        "ts_ms": ts_ms - 3600_000 * 5,
        "published_at": (now - timedelta(hours=5)).isoformat(),
        "event_type": "news",
        "title": "贝莱德 IBIT 净流入创近三周新高",
        "reason": "IBIT 单日净流入 480 M USD，机构仓位持续扩张。",
        "source": "farside.co",
        "risk_action": "accumulate_on_dip",
    },
    {
        "ts_ms": ts_ms - 3600_000 * 8,
        "published_at": (now - timedelta(hours=8)).isoformat(),
        "event_type": "alert",
        "title": "RSI 超买信号（4h）",
        "reason": "4h RSI 上升至 76，警惕技术性回调风险。",
        "source": "derived",
        "risk_action": "partial_take_profit",
    },
    {
        "ts_ms": ts_ms - 3600_000 * 12,
        "published_at": (now - timedelta(hours=12)).isoformat(),
        "event_type": "news",
        "title": "美联储官员讲话暗示下半年降息",
        "reason": "美元指数回落至 101.5，风险资产整体受益。",
        "source": "reuters",
        "risk_action": "hold",
    },
    {
        "ts_ms": ts_ms - 3600_000 * 18,
        "published_at": (now - timedelta(hours=18)).isoformat(),
        "event_type": "position",
        "title": "ETH 现货 ETF 获批传闻升温",
        "reason": "多位 KOL 引用 SEC 流程进展，ETH Gas 价格同步上行。",
        "source": "twitter_snapshot",
        "risk_action": "accumulate",
    },
    {
        "ts_ms": ts_ms - 3600_000 * 22,
        "published_at": (now - timedelta(hours=22)).isoformat(),
        "event_type": "news",
        "title": "交易所净流出 -12K BTC",
        "reason": "过去 24 小时交易所出现明显净流出，投资者倾向持仓离场。",
        "source": "glassnode",
        "risk_action": "hodl",
    },
]
ledger_path = RAW_DIR / f"event_ledger_{stamp}.jsonl"
with open(ledger_path, "w", encoding="utf-8") as f:
    for ev in events:
        f.write(json.dumps(ev, ensure_ascii=False) + "\n")
print(f"[OK] {ledger_path} ({len(events)} rows)")


# -------- Narrative Brief (Markdown) 供 narrative/brief/latest 读取 --------
narrative_brief_md = f"""# 叙事分析简报

**生成时间**: {iso}
**整体情绪指数**: {registry['overall_sentiment']:.2f}（偏乐观）
**活跃叙事数量**: {len(narratives)}

## 📖 叙事概览

{chr(10).join(f"- **{n['name']}**: {n['summary']}（情绪 {n['sentiment']:+.2f}）" for n in narratives)}

## 🧠 叙事分解（Top 3）

### 1. ETF 机构持续买入
信心: 0.82 | 证据: 8 条 | 情绪: +0.45

BTC ETF 连续净流入，机构买家在 64-66K 区间执行积极建仓策略。
这是当前推动价格的最强叙事。

### 2. 宏观降息预期升温
信心: 0.76 | 证据: 5 条 | 情绪: +0.38

美联储官员讲话暗示下半年可能开始降息，美元走弱利好风险资产。

### 3. ETH 现货 ETF 获批预期
信心: 0.70 | 证据: 6 条 | 情绪: +0.41

市场预期 ETH 现货 ETF 可能在未来 1-2 个月获批，
带动以太坊链上活动与 Gas 同步上升。

## ⚠️ 风险叙事

- **监管不确定性溢价**: SEC 对 DeFi 框架磋商仍在进行
- **RSI 超买风险**: 短线技术指标过热，警惕回调

## 🎯 叙事建议

- 主叙事多头仍占优，但需注意超买回调风险
- 关注 ETF 资金流是否持续
- Alt 轮动扩散，但应精选流动性标的
"""
write_text(NARRATIVE_DIR / f"narrative_brief_{stamp}.md", narrative_brief_md)

print("\n✅ 所有基本面数据文件已生成")
